logiq-flash:
  replicaCount: 4
  replicaCountMl: 2
  replicaCountSync: 2
  service:
    type: NodePort
  image:
    repository: logiqai/flash
    tag: v3.20.3
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 100Gi
    ml_size: 20Gi
  metrics:
    serviceMonitor:
      enabled: true
    selector:
      release: prometheus
  resources:
    ingest:
      requests:
        cpu: 1250m
        memory: 3500Mi
      limits:
        memory: 4000Mi
    sidecarQuery:
      requests:
        memory: 100Mi
      limits:
        memory: 4000Mi
    sidecarTracing:
      requests:
        memory: 20Mi
      limits:
        memory: 4000Mi
    ml:
      requests:
        cpu: 100m
        memory: 900Mi
      limits:
        memory: 1500Mi
    sidecarMlTracing:
      requests:
        memory: 20Mi
      limits:
        memory: 1500Mi
    sync:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        memory: 750Mi
  logflow_only:
    enabled: false
    args: -object_writers=1 -max_bytes_per_sec=833331
  kafka_client:
    enabled: false
    kafka_args: -kafka_ca_cert_path=/flash/kafka/ca.crt -kafka_client_key_path=/flash/kafka/tls.key -kafka_client_cert_path=/flash/kafka/tls.crt
  secrets_name: my-ascent-ingest
flash-discovery:
  fullnameOverride: flash-discovery
  image:
    repository: logiqai/flash-discovery
    tag: 2.0.3
    pullPolicy: IfNotPresent
  replicaCountDiscovery: 2
  persistence:
    enabled: true
    size: 2Gi
  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 16Mi
redis:
  enabled: true
  fullnameOverride: redis
  usePassword: false
  cluster:
    slaveCount: 0
  master:
    resources:
      limits:
        memory: 6000Mi
      requests:
        memory: 500Mi
        cpu: 100m
    disableCommands: []
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - redis
          topologyKey: kubernetes.io/hostname
    persistence:
      enabled: false
  slave:
    disableCommands: []
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - redis
          topologyKey: kubernetes.io/hostname
    persistence:
      enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    selector:
      release: prometheus
  podSecurityPolicy:
    create: true
    rbac:
      create: true
      role:
        rules:
        - apiGroups:
          - policy
          resources:
          - podsecuritypolicies
          verbs:
          - use
          resourceNames:
          - redis
  securityContext:
    enable: true
    fsGroup: 1001
    runAsUser: 1001
  serviceAccount:
    create: true
    name: redis
postgres:
  enabled: true
  fullnameOverride: postgres
  postgresqlPostgresPassword: '##YOUR_POSTGRES_ROOT_PASSWORD##'
  postgresqlUsername: postgres
  postgresqlDatabase: postgres
  postgresqlPassword: '##YOUR_POSTGRES_PASSWORD##'
  postgresqlExtendedConf:
    maxConnections: '400'
    sharedBuffers: 1024MB
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    additionalLabels:
      release: prometheus
  persistence:
    size: 20Gi
  resources:
    limits:
      memory: 20000Mi
    requests:
      memory: 4000Mi
      cpu: 500m
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  serviceAccount:
    enabled: true
    name: postgres
flash-coffee:
  service:
    type: ClusterIP
  coffee:
    replicaCount: 2
    image:
      repository: logiqai/flash-brew-coffee
      tag: brew.v3.21.3
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 1000Mi
  coffee_worker:
    replicaCount: 3
    image:
      repository: logiqai/flash-brew-coffee
      tag: brew.v3.21.3
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 600Mi
        cpu: 100m
      limits:
        memory: 2000Mi
thanos:
  createObjstoreSecret: true
  receive:
    logLevel: info
    service:
      type: ClusterIP
    enabled: true
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
  query:
    enabled: true
    dnsDiscovery:
      enabled: true
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
  bucketweb:
    enabled: true
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
  compactor:
    enabled: true
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  storegateway:
    enabled: true
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
  ruler:
    enabled: true
    alertmanagers:
    - prometheus-alertmanager
    existingConfigmap: thanos-ruler-configmap
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
gateway:
  tls:
    enabled: true
    secretName: my-ascent-ingress
envoyGateway:
  enabled: true
  gatewayClass:
    controllerName: gateway.envoyproxy.io/gatewayclass-controller
    description: Envoy Gateway for Apica Ascent
  envoyProxy:
    provider:
      type: Kubernetes
      service:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
  listeners:
    http:
      port: 80
      protocol: HTTP
    https:
      port: 443
      protocol: HTTPS
    tcp:
    - name: tcp-9999
      port: 9999
      protocol: TCP
    - name: tcp-8081
      port: 8081
      protocol: TCP
    - name: tcp-14250
      port: 14250
      protocol: TCP
    - name: tcp-20514
      port: 20514
      protocol: TCP
    - name: tcp-14268
      port: 14268
      protocol: TCP
  compressor:
    enabled: true
    quality: 6
apicaTLSSecret:
  enabled: true
prometheus:
  fullnameOverride: prometheus
  persistence:
    enabled: true
    size: 20Gi
  alertmanager:
    enabled: true
    replicaCount: 1
    persistence:
      enabled: true
      size: 20Gi
  prometheus:
    enabled: true
    resources:
      requests:
        memory: 500Mi
        cpu: 300m
      limits:
        memory: 6000Mi
    replicaCount: 2
    persistence:
      enabled: true
      size: 20Gi
    thanos:
      create: true
      objectStorageConfig:
        secretName: thanos-objstore-secret
        secretKey: objstore.yml
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          memory: 200Mi
  operator:
    enabled: true
    replicaCount: 1
  kube-state-metrics:
    replicaCount: 1
  exporters:
    node-exporter:
      enabled: false
    kube-state-metrics:
      enabled: true
  node-exporter:
    enabled: false
    replicaCount: 0
grafana:
  fullnameOverride: grafana
logiqctl:
  image:
    repository: logiqai/logiqctl
    tag: 2.0.4
    pullPolicy: IfNotPresent
global:
  domain: '##YOUR_DOMAIN##'
  imageRegistry: docker.io
  kubeDistributor:
    enabled: false
  cloudProvider: aws
  nodePort:
    enabled: false
    ports:
      flash: null
      flashMl: null
      thanosReceiveHttp: null
      thanosReceiveGrpc: null
      thanosReceiveRemote: null
  createStorageClass: false
  enableMetricsServer: false
  sharedSecretName: logiq-shared-secret
  nodeSelectors:
    enabled: false
    label: apica-node-pool
    ingest: ingest
    infra: base
    other: base
    db: common
    cache: common
    ingest_sync: base
  taints:
    enabled: false
    ingest: flash
    infra: infra
    other: coffee
    db: db
    cache: cache
    ingest_sync: sync
  job:
    ttlSecondsAfterFinished: 100
  toolbox:
    image:
      repository: logiqai/toolbox
      tag: 2.0.1
  environment:
    logiq_flash_host: logiq-flash
    logiq_flash_port: 9999
    redis_opts: true
    redis_host: redis-master
    redis_port: '6379'
    postgres_host: postgres
    postgres_port: '5432'
    postgres_user: postgres
    postgres_password: '##YOUR_POSTGRES_PASSWORD##'
    postgres_db: postgres
    postgres_coffee_db: coffee
    s3_url: '##YOUR_S3_URL##'
    s3_access: '##YOUR_S3_ACCESS_KEY##'
    s3_secret: '##YOUR_S3_ACCESS_SECRET##'
    AWS_ACCESS_KEY_ID: '##YOUR_S3_ACCESS_KEY##'
    AWS_SECRET_ACCESS_KEY: '##YOUR_S3_ACCESS_KEY##'
    s3_bucket: '##YOUR_S3_BUCKET##'
    s3_region: '##YOUR_S3_REGION##'
    admin_name: '##ADMIN_ACCOUNT_NAME##'
    admin_password: '##ADMIN_ACCOUNT_PASSWORD##'
    admin_org: '##ADMIN_ORGANIZATION##'
    admin_email: '##ADMIN_EMAIL##'
    license: license/license.jws
    upload_dashboard: false
    cluster_id: LOGIQ
    awsServiceEndpoint: '##YOUR_S3_URL##'
    external_cert_crt: ''
    external_cert_key: ''
    internal_cert_crt: ''
    internal_cert_key: ''
    extraflag: -hauler-node-affinity=false --tail_longpoll=true -persist=true
  persistence:
    storageClass: openebs-hostpath
  chart:
    prometheus: true
    postgres: true
    redis: true
    s3gateway: false
    grafana: false
vault:
  enabled: false
  serverCaCertificateB64: ''
  serverAddress: https://vault.example.com
  authMount: k8s-clustername
  kafkaClientCertDomain: example.com
